//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoconfigurationEmail.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoconfigurationEmail.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check Username and Password.
        /// </summary>
        internal static string Connection_CheckUsernamePassword {
            get {
                return ResourceManager.GetString("Connection_CheckUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check email settings.
        /// </summary>
        internal static string Connection_ContactAdmin {
            get {
                return ResourceManager.GetString("Connection_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP connection:.
        /// </summary>
        internal static string Connection_ImapFailed {
            get {
                return ResourceManager.GetString("Connection_ImapFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP connection:.
        /// </summary>
        internal static string Connection_SmtpFailed {
            get {
                return ResourceManager.GetString("Connection_SmtpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occuried.
        /// </summary>
        internal static string Connection_UnexpectedException {
            get {
                return ResourceManager.GetString("Connection_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager1@themsteam.com.
        /// </summary>
        internal static string FromEmail {
            get {
                return ResourceManager.GetString("FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoconfig.thunderbird.net/v1.1/.
        /// </summary>
        internal static string Ispdb_Url {
            get {
                return ResourceManager.GetString("Ispdb_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string OverSsl {
            get {
                return ResourceManager.GetString("OverSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345,qwerty.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSTEAM\Manager1.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
